In [2]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50, 5))
df1 = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index = range(1,51))
df1

     國文   英文  數學  地理   歷史
1    75   76  50  67   65
2    96   87  61  76   80
3    57   50  93  78   98
4    73  100  71  55   73
5    62   51  79  82   99
6    51   93  80  83   59
7    96   94  92  71   50
8    89   86  65  81   82
9    98   89  71  68   70
10   58   89  93  78   94
11   66   60  86  98   96
12   79   54  55  98   66
13   86   75  73  78   76
14   59   93  73  57   79
15   51   82  52  85   51
16   87   97  96  84   75
17   88   71  91  90   54
18   78   50  62  55  100
19   89   74  96  79   66
20   96   74  93  88   86
21   62   88  80  76   96
22   91   77  53  70   95
23   76   85  77  77   73
24  100   85  77  63   86
25   94   81  81  99   84
26   62   57  57  90   66
27   84   86  57  84   98
28   96   84  85  69   98
29   88   55  92  82   79
30   69  100  64  74   75
31   58   70  75  83   66
32   68   75  88  96   64
33  100   87  76  93   52
34   77   66  80  98   68
35   57   64  78  75   59
36   98   57  68  69   53
37   89   58  89  95   68
38   51   79  56  61   90
39   77   72  85  78   54
40   89   59  93  50   53
41   86   55  86  76   78
42   81   68  93  97   94
43   99   71  60  65   78
44   72   98  81  51   59
45   54   92  82  82   92
46   97   95  76  53   67
47   71   61  65  79   97
48   88   71  51  59   50
49   94   88  85  84   94
50   90   63  73  73   89

In [3]:
df1.index.name = '學號'
df1.columns.name = "科目"

In [4]:
df1.loc[1].sum()

np.int64(333)

In [5]:
sum = df1.sum(axis=1)

average = sum / 5

In [6]:
df1['總分'] = sum
df1['平均'] = average
df1

科目   國文   英文  數學  地理   歷史   總分    平均
學號
1    75   76  50  67   65  333  66.6
2    96   87  61  76   80  400  80.0
3    57   50  93  78   98  376  75.2
4    73  100  71  55   73  372  74.4
5    62   51  79  82   99  373  74.6
6    51   93  80  83   59  366  73.2
7    96   94  92  71   50  403  80.6
8    89   86  65  81   82  403  80.6
9    98   89  71  68   70  396  79.2
10   58   89  93  78   94  412  82.4
11   66   60  86  98   96  406  81.2
12   79   54  55  98   66  352  70.4
13   86   75  73  78   76  388  77.6
14   59   93  73  57   79  361  72.2
15   51   82  52  85   51  321  64.2
16   87   97  96  84   75  439  87.8
17   88   71  91  90   54  394  78.8
18   78   50  62  55  100  345  69.0
19   89   74  96  79   66  404  80.8
20   96   74  93  88   86  437  87.4
21   62   88  80  76   96  402  80.4
22   91   77  53  70   95  386  77.2
23   76   85  77  77   73  388  77.6
24  100   85  77  63   86  411  82.2
25   94   81  81  99   84  439  87.8
26   62   57  57  90   66  332  66.4
27   84   86  57  84   98  409  81.8
28   96   84  85  69   98  432  86.4
29   88   55  92  82   79  396  79.2
30   69  100  64  74   75  382  76.4
31   58   70  75  83   66  352  70.4
32   68   75  88  96   64  391  78.2
33  100   87  76  93   52  408  81.6
34   77   66  80  98   68  389  77.8
35   57   64  78  75   59  333  66.6
36   98   57  68  69   53  345  69.0
37   89   58  89  95   68  399  79.8
38   51   79  56  61   90  337  67.4
39   77   72  85  78   54  366  73.2
40   89   59  93  50   53  344  68.8
41   86   55  86  76   78  381  76.2
42   81   68  93  97   94  433  86.6
43   99   71  60  65   78  373  74.6
44   72   98  81  51   59  361  72.2
45   54   92  82  82   92  402  80.4
46   97   95  76  53   67  388  77.6
47   71   61  65  79   97  373  74.6
48   88   71  51  59   50  319  63.8
49   94   88  85  84   94  445  89.0
50   90   63  73  73   89  388  77.6

In [7]:
english_series = df1['英文'] < 60
df1[english_series]

科目  國文  英文  數學  地理   歷史   總分    平均
學號
3   57  50  93  78   98  376  75.2
5   62  51  79  82   99  373  74.6
12  79  54  55  98   66  352  70.4
18  78  50  62  55  100  345  69.0
26  62  57  57  90   66  332  66.4
29  88  55  92  82   79  396  79.2
36  98  57  68  69   53  345  69.0
37  89  58  89  95   68  399  79.8
40  89  59  93  50   53  344  68.8
41  86  55  86  76   78  381  76.2

In [8]:
for x in df1['英文'] < 60:
    print(x)

False
False
True
False
True
False
False
False
False
False
False
True
False
False
False
False
False
True
False
False
False
False
False
False
False
True
False
False
True
False
False
False
False
False
False
True
True
False
False
True
True
False
False
False
False
False
False
False
False
False